[project]
name = "ft-qmetro"
version = "0.1.0"
description = "Numerical analysis for \"Achieving the Heisenberg limit using fault-tolerant quantum error correction\""
authors = [
    {name = "Himanshu Sahu"}
]
license = {text = "The MIT License"}
requires-python = ">=3.10"
dependencies = [
    "bokeh (==3.7.2)",
    "contourpy (==1.3.0)",
    "cycler (==0.12.1)",
    "dill (==0.3.9)",
    "fonttools (==4.54.1)",
    "frozendict (==2.4.6)",
    "frozenlist (==1.5.0)",
    "fusion-blossom (==0.2.10)",
    "ipydatawidgets (==4.3.5)",
    "joblib (==1.4.2)",
    "jsonpickle (==4.0.5)",
    "kiwisolver (==1.4.7)",
    "matplotlib (==3.9.2)",
    "mpmath (==1.3.0)",
    "mwpf (==0.2.9)",
    "narwhals (==1.33.0)",
    "networkx (==3.4.2)",
    "numpy (==1.26.4)",
    "pandas (==2.2.3)",
    "pbr (==6.1.0)",
    "pillow (==11.0.0)",
    "plotly (==6.0.1)",
    "pptree (==3.1)",
    "pymatching (==2.2.1)",
    "pyparsing (==3.2.0)",
    "pyqt6 (==6.7.1)",
    "pythreejs (==2.4.2)",
    "pytz (==2025.1)",
    "pyvis (==0.3.2)",
    "qiskit-aer (==0.15.1)",
    "qsurface (==0.1.5)",
    "rustworkx (==0.15.1)",
    "scipy (==1.14.1)",
    "seaborn (==0.13.2)",
    "sinter (==1.14.0)",
    "stevedore (==5.3.0)",
    "stim (==1.14.0)",
    "sympy (==1.13.3)",
    "tqdm (==4.66.6)",
    "traittypes (==0.2.3)",
    "typing-extensions (==4.15.0)",
    "tzdata (==2025.1)",
    "wcwidth (==0.2.13)",
    "webencodings (==0.5.1)",
    "xyzservices (==2025.1.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
